### ISSUE TITLE
Slicer_VERSION versus APPLICATION_VERSION

### ISSUE THREAD

**Issue by phcerdan** [KitwareMedical/SlicerCustomAppTemplate#2] opened 2018-07-30 19:08 UTC
https://github.com/KitwareMedical/SlicerCustomAppTemplate/blob/5d91a64b3dc0b03f81dcc4357393dc540ce2b075/%7B%7Bcookiecutter.project_name%7D%7D/CMakeLists.txt#L31-L35

Shouldn't that be?

```cmake
set(APPLICATION_VERSION_MAJOR       "0") 
set(APPLICATION_VERSION_MINOR       "1") 
set(APPLICATION_VERSION_PATCH       "0") 
project(${APPLICATION_NAME} VERSION "${APPLICATION_VERSION_MAJOR}.${APPLICATION_VERSION_MINOR}.${APPLICATION_VERSION_PATCH}") 
```

Thanks!

**Comment by jcfr** [comment] 2018-07-30 19:16
In the current Slicer, I don't think there any differentiation of version of the app and version of Slicer, this is currently being added .

**Comment by phcerdan** [comment] 2018-07-30 20:57
Thanks @jcfr, that's great, but the name is then misleading, the SlicerSALT dev is not setting the Slicer_VERSION here.

`this is currently being added`. What do you mean? Is it local WIP, or is there any branch out-there?
Should I fix this in a PR or let it be waiting for your changes?
Thanks

**Comment by jcfr** [comment] 2018-07-30 20:59
> What do you mean? Is it local WIP, or is there any branch out-there?

Work in progress locally on my workstation.  

I plan to push a topic for review by the end of the afternoon

**Comment by jcfr** [comment] 2018-07-30 23:48
Closing. Duplicate of #3

**Comment by jcfr** [comment] 2018-07-30 23:48
> What do you mean? Is it local WIP, or is there any branch out-there?

See https://github.com/Slicer/Slicer/pull/997

**Closed by jcfr** 2018-07-30 23:48 UTC
